# PPO parameters

# Detailed explanation for each hyper parameter can be found in ray/rllib/agents/ppo/ippo.py

algo_args:
  use_gae: True
  lambda: 0.95 #1.0
  kl_coeff: 0.3 #0.2
  batch_episode: 500
  num_sgd_iter: 15
  vf_loss_coeff: 1.0
  lr: 0.0005
  entropy_coeff: 0.01 #0.01
  clip_param: 0.3 # 0.3
  vf_clip_param: 2000.0
  batch_mode: "complete_episodes"

